### ISSUE TITLE
Store Method.

### ISSUE THREAD

**Issue by charliekaks** [forfuturellc/node-sequential-ids#4]
Please, can you outline clearly how the store method described in the documentation is used? Is it part of the library or a method that one chooses to use when storing the ids? Also, where do the ids come in in the store method?

**Comment by GochoMugo** [comment]
I guess the documentation is a bit unclear.

In the README, section [Usage](https://github.com/forfuturellc/node-sequential-ids#usage), the very first comments in the codeblock explain this, i.e.

```js
// assuming `db` is a variable holding a database connection with the
// method `.store(key, value)`
```

The callback provided in option `store` in the `options` argument to `Generator#add(key, [options])` is for you to implement as you wish. You can therefore use any DB/store to save the already generated IDs.

**Comment by charliekaks** [comment]
Thank you for the response that clears up a few things. Just a follow up does ``restore`` argument in options keep the latest id generated or is it used a starting point to generate ids only.

**Comment by GochoMugo** [comment]
You'd provide the last generated ID in the `restore` option (usually you'd store the generated IDs using the `store` callback as explained in my comment above) when constructing the generator. The generator would pick up from there.

**Comment by charliekaks** [comment]
Thank you very much. I am using mongodb would you have any suggestions on how the ``store`` option would look like I can't seem to figure it out.

**Comment by GochoMugo** [comment]
That highly depends on what you're trying to achieve. Any more info?

**Comment by charliekaks** [comment]
What I am looking to do is to generate sequential ids ``A-001, A-002`` and so on. I want to generate ids when the data is created.
