### ISSUE TITLE
Port being used

### ISSUE THREAD

**Issue by charliekaks** [forfuturellc/node-sequential-ids#6]
I finally figured out how to use the library. However, I get this error  ````Error: listen EADDRINUSE :::9876````.It occurs when I create one Id then create another within the same session.

**Comment by charliekaks** [comment]
Sorry silly mistake, I was rerunning generator.

**Comment by charliekaks** [comment]
Please can you explain to me how the ports work. I thought I fixed it but that was not the case

**Comment by GochoMugo** [comment]
Is it possible that you are creating multiple generators and invoking `Generator#start()` on them (using the default ports)?

**Comment by charliekaks** [comment]
This is code am running.
```
let ids = [];
        clientNumber.findById('5d2984d85b77070cff737276',(err, cnumbers)=>{
            cnumbers.client_numbers.forEach(element => {
                console.log(element.client_number);
                ids.push(element.client_number);    
            });
            console.log(ids)
            var generator = new sequential.Generator({
                digits: 4,
                letters: 3,
                restore: ids[ids.length - 1]
            });
            generator.start();

            let genId = generator.generate();
            // console.log(genId);
            cnumbers.clients.create({"client_number":genId})
            ctx.req.body.client_number = genId;
```

**Comment by GochoMugo** [comment]
You just need to create the generator once in your process' lifetime. Also,
if you aren't intending to use accessors, you don't need to invoke
`Generator#start()`.

**Comment by charliekaks** [comment]
Thanks it works now.
